version: '3.4'

services:
  patient.management:
    image: ${DOCKER_REGISTRY-}patientmanagement
    container_name: patient.management
    build:
      context: PatientManagement
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - rabbitmq
      - patient.database 
      - patient.eventstore 

  patient.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: patient.database
    ports:
      - "14331:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
    volumes:
      - "./_Server/Database/PatientManagement:/var/opt/mssql/data"

  patient.eventstore:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: patient.eventstore
    ports:
      - "14332:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
    volumes:
      - "./_Server/EventStore/PatientManagement:/var/opt/mssql/data"

  appointment.management:
    image: ${DOCKER_REGISTRY-}appointmentmanagement
    container_name: appointment.management
    build:
      context: AppointmentManagement
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
      - "5003:5003"
    depends_on:
      - rabbitmq
      - appointment.database 
      - appointment.eventstore 

  appointment.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: appointment.database
    ports:
      - "14333:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
    volumes:
      - "./_Server/Database/AppointmentManagement:/var/opt/mssql/data"

  appointment.eventstore:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: appointment.eventstore
    ports:
      - "14334:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
    volumes:
      - "./_Server/EventStore/AppointmentManagement:/var/opt/mssql/data"

  dossier.management:
    image: ${DOCKER_REGISTRY-}dossiermanagement
    container_name: dossier.management
    build:
      context: DossierManagement
      dockerfile: Dockerfile
    ports:
      - "5006:5006"
      - "5007:5007"
    depends_on:
      - rabbitmq
      - dossier.database 
      - dossier.eventstore 

  dossier.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dossier.database
    ports:
      - "14337:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
    volumes:
      - "./_Server/Database/DossierManagement:/var/opt/mssql/data"

  dossier.eventstore:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dossier.eventstore
    ports:
      - "14338:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
    volumes:
      - "./_Server/EventStore/DossierManagement:/var/opt/mssql/data"

  consultancy:
    image: ${DOCKER_REGISTRY-}consultancy
    container_name: consultancy
    build:
        context: Consultancy
        dockerfile: Dockerfile
    ports:
        - "5004:5004"
        - "5005:5005"
    depends_on:
      - rabbitmq
      - consultancy.database 
      - consultancy.eventstore 

  consultancy.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: consultancy.database
    ports:
      - "14335:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
    volumes:
      - "./_Server/Database/Consultancy:/var/opt/mssql/data"

  consultancy.eventstore:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: consultancy.eventstore
    ports:
      - "14336:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
    volumes:
      - "./_Server/EventStore/Consultancy:/var/opt/mssql/data"

  staff.management:
    image: ${DOCKER_REGISTRY-}staffmanagement
    container_name: staff.management
    build:
      context: StaffManagement
      dockerfile: Dockerfile
    ports:
      - "5006:5006"
      - "5007:5007"
    environment:
      - DATABASE_HOST_READ=staff.database
      - DATABASE_HOST_WRITE=staff.eventstore
      - DATABASE_NAME_READ=StaffDb
      - DATABASE_NAME_WRITE=StaffEventStore
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_PORT=5432
    depends_on:
      - staff.database
      - staff.eventstore
      - rabbitmq

  staff.database:
    image: postgres
    container_name: staff.database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: StaffDb
    ports:
      - "5432:5432"
    volumes:
      - ./StaffManagement/staffDb.script.sql:/docker-entrypoint-initdb.d/staffDb.script.sql

  staff.eventstore:
    image: postgres
    container_name: staff.eventstore
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: StaffEventStore
    ports:
      - "5433:5432"
    volumes:
      - ./StaffManagement/eventStore.script.sql:/docker-entrypoint-initdb.d/eventStore.script.sql


  hospital.management:
    image: ${DOCKER_REGISTRY-}hospitalmanagement
    container_name: hospital.management
    build:
      context: HospitalManagement
      dockerfile: Dockerfile
    ports:
      - "5008:5008"
      - "500:5009"
    environment:
      - DATABASE_HOST_READ=hospital.database
      - DATABASE_HOST_WRITE=hospital.eventstore
      - DATABASE_NAME_READ=HospitalDb
      - DATABASE_NAME_WRITE=HospitalEventStore
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_PORT=5432
    depends_on:
      - hospital.database
      - hospital.eventstore
      - rabbitmq

  hospital.database:
    image: postgres
    container_name: hospital.database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: HospitalDb
    ports:
      - "5434:5432"
    volumes:
      - ./HospitalManagement/hospitalDb.script.sql:/docker-entrypoint-initdb.d/hospitalDb.script.sql
    
  hospital.eventstore:
    image: postgres
    container_name: hospital.eventstore
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: HospitalEventStore
    ports:
      - "5435:5432"
    volumes:
      - ./HospitalManagement/eventStore.script.sql:/docker-entrypoint-initdb.d/eventStore.script.sql

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    depends_on:
      - patient.eventstore
      - patient.database
      - appointment.eventstore
      - appointment.database
      - consultancy.database
      - consultancy.eventstore
      - hospital.database
      - hospital.eventstore 
      - staff.database
      - staff.eventstore 
      - dossier.eventstore
      - dossier.database
