version: '3.4'

services:
  patient.management:
    image: ${DOCKER_REGISTRY-}patientmanagement
    container_name: patient.management
    build:
      context: PatientManagement
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"

  patient.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: patient.database
    ports:
      - "14331:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
    volumes:
      - "./_Server/Database/PatientManagement:/var/opt/mssql/data"

  patient.eventstore:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: patient.eventstore
    ports:
      - "14332:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
    volumes:
      - "./_Server/EventStore/PatientManagement:/var/opt/mssql/data"

  appointment.management:
    image: ${DOCKER_REGISTRY-}appointmentmanagement
    container_name: appointment.management
    build:
      context: AppointmentManagement
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
      - "5003:5003"

  appointment.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: appointment.database
    ports:
      - "14333:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
    volumes:
      - "./_Server/Database/AppointmentManagement:/var/opt/mssql/data"

  appointment.eventstore:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: appointment.eventstore
    ports:
      - "14334:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
    volumes:
      - "./_Server/EventStore/AppointmentManagement:/var/opt/mssql/data"

  dossier.management:
    image: ${DOCKER_REGISTRY-}dossiermanagement
    container_name: dossier.management
    build:
      context: DossierManagement
      dockerfile: Dockerfile
    ports:
      - "5006:5006"
      - "5007:5007"

  dossier.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dossier.database
    ports:
      - "14337:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
    volumes:
      - "./_Server/Database/DossierManagement:/var/opt/mssql/data"

  dossier.eventstore:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dossier.eventstore
    ports:
      - "14338:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
    volumes:
      - "./_Server/EventStore/DossierManagement:/var/opt/mssql/data"

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    depends_on:
      - patient.eventstore
      - patient.database
      - appointment.eventstore
      - appointment.database      
      - dossier.eventstore
      - dossier.database
