// <auto-generated />
using System;
using DossierManagement.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DossierManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DossierManagement.Features.Dossier.Consult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DossierId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DossierId");

                    b.ToTable("Consults");
                });

            modelBuilder.Entity("DossierManagement.Features.Dossier.Dossier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Dossiers");
                });

            modelBuilder.Entity("DossierManagement.Features.Dossier.Medication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DossierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Medicine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DossierId");

                    b.ToTable("Medication");
                });

            modelBuilder.Entity("DossierManagement.Features.Dossier.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BSN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("DossierManagement.Features.Dossier.Result", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DossierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DossierId");

                    b.ToTable("Result");
                });

            modelBuilder.Entity("DossierManagement.Features.Dossier.Consult", b =>
                {
                    b.HasOne("DossierManagement.Features.Dossier.Dossier", null)
                        .WithMany("Consults")
                        .HasForeignKey("DossierId");
                });

            modelBuilder.Entity("DossierManagement.Features.Dossier.Dossier", b =>
                {
                    b.HasOne("DossierManagement.Features.Dossier.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DossierManagement.Features.Dossier.Medication", b =>
                {
                    b.HasOne("DossierManagement.Features.Dossier.Dossier", null)
                        .WithMany("Medications")
                        .HasForeignKey("DossierId");
                });

            modelBuilder.Entity("DossierManagement.Features.Dossier.Result", b =>
                {
                    b.HasOne("DossierManagement.Features.Dossier.Dossier", null)
                        .WithMany("Results")
                        .HasForeignKey("DossierId");
                });

            modelBuilder.Entity("DossierManagement.Features.Dossier.Dossier", b =>
                {
                    b.Navigation("Consults");

                    b.Navigation("Medications");

                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
